---
- name: install the nginx
  ansible.builtin.yum:
    name: "{{web_package}}"
    state: present
- name: start and enable nginx server
  ansible.builtin.service:
    name: "{{web_service}}"
    state: started
    enabled: yes
- name: add template info
  ansible.builtin.template:
    src: webcontent.j2
    dest: /usr/share/nginx/html/index.html
- name: add services to firewall
  ansible.posix.firewalld:
    service: "{{web_protocol}}"
    state: enabled
    immediate: yes
    permanent: yes
  notify: restart nginx 

